
CREATE SCHEMA IF NOT EXISTS IDTEST;

CREATE EXTENSION IF NOT EXISTS postgis;

-- CATALOG STATE
CREATE TABLE IDTEST.CID_STATE (
     CPK_STATE_ID       BIGSERIAL       NOT NULL -- PK ARTIFICIAL
    ,CCK_CVE_ENT        BIGINT          NOT NULL -- CK - LLAVE CANDIDATA
    ,CIN_GID            INT             NOT NULL
    ,CVC_NOM_ENT        VARCHAR(100)    NOT NULL
    ,CVC_NOMBRE_IGG     VARCHAR(100)    NOT NULL
    ,CDT_AUDIT_RECORD   TIMESTAMP DEFAULT NOW() NOT NULL
    ,CONSTRAINT PK_CID_STATE PRIMARY KEY (CPK_STATE_ID)
    ,CONSTRAINT UQ1_STATE_CVE_ENT UNIQUE (CCK_CVE_ENT)
);

-- CATALOG MUNICIPALITY
CREATE TABLE IDTEST.CID_GEOGRAPHY ( -- NUNICIPIO O GEOGRAFIA? 
     CPK_GEOGRAPHY_ID BIGSERIAL      NOT NULL -- PK ARTIFICIAL
    ,CFK_CVE_ENT        BIGINT          NOT NULL
    ,CBI_CVE_MUN        BIGINT          NOT NULL
    ,CVC_NOMGEO         VARCHAR(1500)    NULL    -- NOMBRE DE LA COLONIA/LOCALIDAD
    ,CIN_EPSG           INT             DEFAULT 4326 NOT NULL
    ,CCK_CVEGEO         VARCHAR(30)     NOT NULL
    ,CIN_ID             INT             NOT NULL -- CONSECUTIVO DE CADA MUNICIPIO POR ESTADO
    ,CGO_GEOM               GEOMETRY(Geometry, 4326) -- Point / Geometry
    ,CDT_AUDIT_RECORD   TIMESTAMP DEFAULT NOW() NOT NULL
    ,CONSTRAINT PK_CID_GEOGRAPHY PRIMARY KEY (CPK_GEOGRAPHY_ID)
    ,CONSTRAINT FK_CID_GEOGRAPHY_STATE FOREIGN KEY (CFK_CVE_ENT) 
        REFERENCES IDTEST.CID_STATE(CCK_CVE_ENT)
    ,CONSTRAINT UQ1_CID_GEOGRAPHY_CVE_ENT_ID UNIQUE (CFK_CVE_ENT,CBI_CVE_MUN,CIN_ID)
    ,CONSTRAINT UQ2_CID_GEOGRAPHY_CVEGEO UNIQUE (CCK_CVEGEO)
);

-- Índice espacial indispensable para consultas rápidas en el mapa
CREATE INDEX IX1_CID_GEOGRAPHY_CVE_ENT ON IDTEST.CID_GEOGRAPHY (CFK_CVE_ENT);
CREATE INDEX IX2_CID_GEOGRAPHY_GEOM ON IDTEST.CID_GEOGRAPHY USING GIST(CGO_GEOM);

-- FACT TABLE
CREATE TABLE IDTEST.FID_POPULATION_CENSUS (
     FPK_POPULATION_CENSUS_ID   BIGSERIAL   NOT NULL
    ,FVC_ORIGEN                 VARCHAR(30) NOT NULL
    ,FFK_CVEGEO                 VARCHAR(30) NOT NULL
    ,FBI_P_TOTAL                BIGINT NOT NULL
    ,FBI_POBMAS                 BIGINT NOT NULL
    ,FBI_POBFEM                 BIGINT NOT NULL
    ,FBI_P_0A2                  BIGINT NOT NULL
    ,FBI_P_0A2_M                BIGINT NOT NULL
    ,FBI_P_0A2_F                BIGINT NOT NULL
    ,FBI_P_3YMAS                BIGINT NOT NULL
    ,FBI_P_3YMAS_M              BIGINT NOT NULL
    ,FBI_P_3YMAS_F              BIGINT NOT NULL
    ,FBI_P_5YMAS                BIGINT NOT NULL
    ,FBI_P_5YMAS_M              BIGINT NOT NULL
    ,FBI_P_5YMAS_F              BIGINT NOT NULL
    ,FBI_P_12YMAS               BIGINT NOT NULL
    ,FBI_P_12YMAS_M             BIGINT NOT NULL
    ,FBI_P_12YMAS_F             BIGINT NOT NULL
    ,FBI_P_15YMAS               BIGINT NOT NULL
    ,FBI_P_15YMAS_M             BIGINT NOT NULL
    ,FBI_P_15YMAS_F             BIGINT NOT NULL
    ,FBI_P_18YMAS               BIGINT NOT NULL
    ,FBI_P_18YMAS_M             BIGINT NOT NULL
    ,FBI_P_18YMAS_F             BIGINT NOT NULL
    ,FBI_P_3A5                  BIGINT NOT NULL
    ,FBI_P_3A5_M                BIGINT NOT NULL
    ,FBI_P_3A5_F                BIGINT NOT NULL
    ,FBI_P_6A11                 BIGINT NOT NULL
    ,FBI_P_6A11_M               BIGINT NOT NULL
    ,FBI_P_6A11_F               BIGINT NOT NULL
    ,FBI_P_8A14                 BIGINT NOT NULL
    ,FBI_P_8A14_M               BIGINT NOT NULL
    ,FBI_P_8A14_F               BIGINT NOT NULL
    ,FBI_P_12A14                BIGINT NOT NULL
    ,FBI_P_12A14_M              BIGINT NOT NULL
    ,FBI_P_12A14_F              BIGINT NOT NULL
    ,FBI_P_15A17                BIGINT NOT NULL
    ,FBI_P_15A17_M              BIGINT NOT NULL
    ,FBI_P_15A17_F              BIGINT NOT NULL
    ,FBI_P_18A24                BIGINT NOT NULL
    ,FBI_P_18A24_M              BIGINT NOT NULL
    ,FBI_P_18A24_F              BIGINT NOT NULL
    ,FBI_P_15A49_F              BIGINT NOT NULL
    ,FBI_P_60YMAS               BIGINT NOT NULL
    ,FBI_P_60YMAS_M             BIGINT NOT NULL
    ,FBI_P_60YMAS_F             BIGINT NOT NULL
    ,FDP_REL_H_M                DOUBLE PRECISION NOT NULL
    ,FDP_PROM_HNV               DOUBLE PRECISION NOT NULL
    ,FBI_PNACENT                BIGINT NOT NULL
    ,FBI_PNACENT_M              BIGINT NOT NULL
    ,FBI_PNACENT_F              BIGINT NOT NULL
    ,FBI_PNACOE                 BIGINT NOT NULL
    ,FBI_PNACOE_M               BIGINT NOT NULL
    ,FBI_PNACOE_F               BIGINT NOT NULL
    ,FBI_PRES2005_              BIGINT NOT NULL
    ,FBI_PRES2005_M             BIGINT NOT NULL
    ,FBI_PRES2005_F             BIGINT NOT NULL
    ,FBI_PRESOE05               BIGINT NOT NULL
    ,FBI_PRESOE05_M             BIGINT NOT NULL
    ,FBI_PRESOE05_F             BIGINT NOT NULL
    ,FBI_P3YM_HLI               BIGINT NOT NULL
    ,FBI_P3YM_HLI_M             BIGINT NOT NULL
    ,FBI_P3YM_HLI_F             BIGINT NOT NULL
    ,FBI_P3HLINHE               BIGINT NOT NULL
    ,FBI_P3HLINHE_M             BIGINT NOT NULL
    ,FBI_P3HLINHE_F             BIGINT NOT NULL
    ,FBI_P3HLI_HE               BIGINT NOT NULL
    ,FBI_P3HLI_HE_M             BIGINT NOT NULL
    ,FBI_P3HLI_HE_F             BIGINT NOT NULL
    ,FBI_P5_HLI                 BIGINT NOT NULL
    ,FBI_P5_HLI_NHE             BIGINT NOT NULL
    ,FBI_P5_HLI_HE              BIGINT NOT NULL
    ,FBI_PHOG_IND               BIGINT NOT NULL
    ,FBI_PCON_LIM               BIGINT NOT NULL
    ,FBI_PCLIM_MOT              BIGINT NOT NULL
    ,FBI_PCLIM_VIS              BIGINT NOT NULL
    ,FBI_PCLIM_LENG             BIGINT NOT NULL
    ,FBI_PCLIM_AUD              BIGINT NOT NULL
    ,FBI_PCLIM_MOT2             BIGINT NOT NULL
    ,FBI_PCLIM_MEN              BIGINT NOT NULL
    ,FBI_PCLIM_MEN2             BIGINT NOT NULL
    ,FBI_PSIN_LIM               BIGINT NOT NULL
    ,FBI_P3A5_NOA               BIGINT NOT NULL
    ,FBI_P3A5_NOA_M             BIGINT NOT NULL
    ,FBI_P3A5_NOA_F             BIGINT NOT NULL
    ,FBI_P6A11_NOA              BIGINT NOT NULL
    ,FBI_P6A11_NOAM             BIGINT NOT NULL
    ,FBI_P6A11_NOAF             BIGINT NOT NULL
    ,FBI_P12A14NOA              BIGINT NOT NULL
    ,FBI_P12A14NOAM             BIGINT NOT NULL
    ,FBI_P12A14NOAF             BIGINT NOT NULL
    ,FBI_P15A17A                BIGINT NOT NULL
    ,FBI_P15A17A_M              BIGINT NOT NULL
    ,FBI_P15A17A_F              BIGINT NOT NULL
    ,FBI_P18A24A                BIGINT NOT NULL
    ,FBI_P18A24A_M              BIGINT NOT NULL
    ,FBI_P18A24A_F              BIGINT NOT NULL
    ,FBI_P8A14AN                BIGINT NOT NULL
    ,FBI_P8A14AN_M              BIGINT NOT NULL
    ,FBI_P8A14AN_F              BIGINT NOT NULL
    ,FBI_P15YM_AN               BIGINT NOT NULL
    ,FBI_P15YM_AN_M             BIGINT NOT NULL
    ,FBI_P15YM_AN_F             BIGINT NOT NULL
    ,FBI_P15YM_SE               BIGINT NOT NULL
    ,FBI_P15YM_SE_M             BIGINT NOT NULL
    ,FBI_P15YM_SE_F             BIGINT NOT NULL
    ,FBI_P15PRI_IN              BIGINT NOT NULL
    ,FBI_P15PRI_INM             BIGINT NOT NULL
    ,FBI_P15PRI_INF             BIGINT NOT NULL
    ,FBI_P15PRI_CO              BIGINT NOT NULL
    ,FBI_P15PRI_COM             BIGINT NOT NULL
    ,FBI_P15PRI_COF             BIGINT NOT NULL
    ,FBI_P15SEC_IN              BIGINT NOT NULL
    ,FBI_P15SEC_INM             BIGINT NOT NULL
    ,FBI_P15SEC_INF             BIGINT NOT NULL
    ,FBI_P15SEC_CO              BIGINT NOT NULL
    ,FBI_P15SEC_COM             BIGINT NOT NULL
    ,FBI_P15SEC_COF             BIGINT NOT NULL
    ,FBI_P18YM_PB               BIGINT NOT NULL
    ,FBI_P18YM_PB_M             BIGINT NOT NULL
    ,FBI_P18YM_PB_F             BIGINT NOT NULL
    ,FDP_GRAPROES               DOUBLE PRECISION NOT NULL
    ,FDP_GRAPROES_M             DOUBLE PRECISION NOT NULL
    ,FDP_GRAPROES_F             DOUBLE PRECISION NOT NULL
    ,FBI_PEA                    BIGINT NOT NULL
    ,FBI_PEA_M                  BIGINT NOT NULL
    ,FBI_PEA_F                  BIGINT NOT NULL
    ,FBI_PE_INAC                BIGINT NOT NULL
    ,FBI_PE_INAC_M              BIGINT NOT NULL
    ,FBI_PE_INAC_F              BIGINT NOT NULL
    ,FBI_POCUPADA               BIGINT NOT NULL
    ,FBI_POCUPADA_M             BIGINT NOT NULL
    ,FBI_POCUPADA_F             BIGINT NOT NULL
    ,FBI_PDESOCUP               BIGINT NOT NULL
    ,FBI_PDESOCUP_M             BIGINT NOT NULL
    ,FBI_PDESOCUP_F             BIGINT NOT NULL
    ,FDT_AUDIT_RECORD           TIMESTAMP DEFAULT NOW() NOT NULL
    ,CONSTRAINT PK_POPULATION_CENSUS PRIMARY KEY (FPK_POPULATION_CENSUS_ID)
    ,CONSTRAINT FK_POPULATION_CENSUS_GEOGRAPHY FOREIGN KEY (FFK_CVEGEO) 
        REFERENCES IDTEST.CID_GEOGRAPHY(CCK_CVEGEO)
);

-- Índices para agilizar las consultas dentro de los Stored Procedures
CREATE INDEX IX1_FID_POPULATION_CENSUS_CVEGEO ON IDTEST.FID_POPULATION_CENSUS (FFK_CVEGEO);
CREATE INDEX IX2_FID_POPULATION_CENSUS_TOTAL ON IDTEST.FID_POPULATION_CENSUS (FBI_P_TOTAL);
CREATE INDEX IX3_FID_POPULATION_CENSUS_P15A49_F ON IDTEST.FID_POPULATION_CENSUS (FBI_P_15A49_F DESC);
